## library() calls go here
library(capsule)
library(conflicted)
library(dotenv)
library(fs)
library(ghstars)
library(glue)
library(googlesheets4)
library(here)
library(janitor)
library(knitr)
library(lubridate)
library(polite)
library(RefManageR)
library(rvest)
library(scholar)
library(scales)
library(targets)
library(tarchetypes)
library(TeXCheckR)
library(tidyverse)
library(tools)
library(vitae)
library(withr)
conflict_prefer("filter", "dplyr")
conflict_prefer("select", "dplyr")
conflict_prefer("pluck", "purrr")
