## library() calls go here
library(capsule)
library(conflicted)
library(dotenv)
library(drake)
library(polite)
library(rvest)
library(glue)
library(scholar)
library(RefManageR)
library(tidyverse)
library(ghstars)
library(googlesheets4)
library(vitae)
library(lubridate)
library(TeXCheckR)
library(tools)
library(scales)
conflicted::conflict_prefer("filter", "dplyr")
conflicted::conflict_prefer("select", "dplyr")
conflicted::conflict_prefer("pluck", "purrr")
