---
name: Nicholas
surname: Tierney
position: "Lecturer"
address: "Department of Econometrics and Business Statistics"
www: njtierney.com
email: "nicholas.tierney@gmail.com"
twitter: nj_tierney
github: njtierney
date: "`r format(Sys.time(), '%B %Y')`"
knit: bookdown::render_book
csl: "csl/apa6-cv.csl"
nocite: "@*"
bibliography_articles: "bib/njt-articles.bib"
bibliography_preprints: "bib/njt-pre-prints.bib"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
```

```{r loadd-drake, include = FALSE}
library(drake)
library(magrittr)
library(vitae)
library(glue)
loadd(awards)
loadd(communication)
loadd(education)
loadd(employment)
loadd(grants)
loadd(memberships)
loadd(publications)
loadd(write_pubs)
loadd(software_stars_dl)
loadd(stars)
loadd(service)
loadd(invited_academic)
loadd(paper_in_prep)
loadd(posters)
loadd(teaching)
loadd(workshops)
loadd(talks)
```

```{r setup-ref, include=FALSE}
RefManageR::BibOptions(
  check.entries = FALSE,
  bib.style = "authoryear",
  sorting = "ynt",
  cite.style = "year",
  style = "markdown",
  hyperlink = TRUE,
  dashed = FALSE
)
```

# Education

```{r print-education}
education %>% 
    detailed_entries(what = with, 
                     when = when, 
                     with = what, 
                     where = where, 
                     why = why)
```

# Software

```{r print-software}
# arrange chronologically
# and add star / download count
software_stars_dl %>% 
  arrange(-when) %>% 
  mutate(detailed_why = pmap(
    .l = list(
              stars = stars, 
              downloads = downloads),
    .f = function(why, stars, downloads){
      if (downloads == 0){
        return(c(
                 paste0(stars, " stars")))
               }
      c(
        paste0(stars, " stars"),
        paste0(scales::comma(downloads), " downloads"))
                      }
    )) %>% 
  detailed_entries(
    what = why,
                   # what = map(detailed_why, 
                   #            glue_collapse,
                   #            sep = " \\newline ",
                   when = when,
                   with = what,
                   where = where,
                   why = detailed_why,
                   .protect = FALSE)
```

# Employment

```{r employment}
employment %>% 
  detailed_entries(what = with,
                   when = when,
                   with = what,
                   where = where,
                   why = why)
```

# Published Articles

```{r journals}
journals <- read_bib("bib/njt-articles.bib") %>% 
  filter(str_detect(bib_orig, "journal ")) %>% 
  mutate(journal = subset_remove_curlies(bib_orig)) %>% 
  select(title, journal)

read_bib_distinct("bib/njt-articles.bib") %>% 
  left_join(journals, by = "title") %>% 
  mutate(title = remove_curlies(title),
         detailed_with = embolden_name(author, 
                                       name = "Tierney, Nicholas J."),
         year = as.integer(year)) %>% 
  drop_na(title) %>% 
  arrange(-year) %>% 
  mutate(year = as.character(year)) %>%
  detailed_entries(
    what = detailed_with,
    when = year, 
    with = title, 
    where = journal,
    # add url?
    .protect = FALSE
  )
```

# Book Chapters



# Preprints

```{r preprints-df}
read_bib_distinct("bib/njt-pre-prints.bib") %>% 
  mutate(detailed_with = embolden_name(author, 
                                       name = "Tierney, Nicholas J."),
         title = remove_curlies(title),
         year = as.integer(year)) %>% 
  drop_na(title) %>% 
  arrange(-year) %>% 
  mutate(year = as.character(year)) %>% 
  detailed_entries(
    what = detailed_with,
    when = year, 
    with = title, 
    where = url,
    .protect = FALSE
  ) 
  
```


# Papers in Preparation

```{r paper-in-prep}
paper_in_prep %>% 
  mutate(detailed_with = embolden_name(with)) %>% 
  detailed_entries(
    # what = with, 
    detailed_with,
                   when = when, 
                   with = what, 
                   where = where, 
                   why = why,
    .protect = FALSE)
```

# Presentations

```{r talks}
# make the talk in bold, add the speaker type in brackets after title
talks %>% 
  mutate(why = as.character(why)) %>% 
  detailed_entries(what = glue("{with} ({why})"), 
                   when = when, 
                   with = what, 
                   where = where)
```

# Posters

```{r posters}
# make the talk in bold, add the speaker type in brackets after title
posters %>% 
  mutate(why = as.character(why)) %>% 
  detailed_entries(what = why, 
                   when = when, 
                   with = what, 
                   where = where) 
```

# Grants

```{r grant}
# fix dollar signs
grants
```

# Awards

```{r award}
awards %>% 
    # detailed_entries(what, when, with, where, why)
    detailed_entries(what = why,
                     when = when, 
                     with = with, 
                     where = where)

```

# Service

```{r service}
service
```

<!-- # Professional Experience -->

# Invited Academic

```{r invited-academic}
invited_academic
```

# Communication

```{r communication}
communication
```

# Teaching

```{r teaching}
teaching %>% 
  detailed_entries(what = what, 
                   when = when, 
                   with = with, 
                   where = where, 
                   why = why)
```

# Workshops

```{r workshops}
workshops %>% 
  detailed_entries(what = with, 
                   when = when, 
                   with = what, 
                   where = where, 
                   why = why)
```
